---
name: Test-Run-Plugin-ColorFileVerdicts
version: 0.0105
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: |-
  make the file verdict ("ok", "NOT OK")
  colorful.
license: mit
resources:
  license: http://opensource.org/licenses/mit-license.php
requires:
  Term::ANSIColor: 0
  Test::Run::CmdLine: 0.0110
  Test::Run::Core: 0.0117
build_requires:
  Test::More: 0
  Test::Run::CmdLine::Trap::ProveApp: 0
  Test::Run::Trap::Obj: 0
provides:
  Test::Run::CmdLine::Plugin::ColorFileVerdicts:
    file: lib/Test/Run/CmdLine/Plugin/ColorFileVerdicts.pm
    version: 0.0101
  Test::Run::Plugin::ColorFileVerdicts:
    file: lib/Test/Run/Plugin/ColorFileVerdicts.pm
    version: 0.0105
  Test::Run::Plugin::ColorFileVerdicts::CanonFailedObj:
    file: lib/Test/Run/Plugin/ColorFileVerdicts/CanonFailedObj.pm
  Test::Run::Plugin::ColorFileVerdicts::ColorBase:
    file: lib/Test/Run/Plugin/ColorFileVerdicts/ColorBase.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
