---
name: Test-Run-Plugin-ColorFileVerdicts
version: 0.01
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: |-
  make the file verdict ("ok", "NOT OK")
  colorful.
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
requires:
  Term::ANSIColor: 0
  Test::Run::CmdLine: 0
  Test::Run::Core: 0.0109
build_requires:
  Test::More: 0
  Test::Trap: 0
provides:
  Test::Run::CmdLine::Plugin::ColorFileVerdicts:
    file: lib/Test/Run/CmdLine/Plugin/ColorFileVerdicts.pm
    version: 0.01
  Test::Run::Plugin::ColorFileVerdicts:
    file: lib/Test/Run/Plugin/ColorFileVerdicts.pm
    version: 0.01
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
