---
abstract: "make the file verdict (\"ok\", \"NOT OK\")"
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::More: 0
  Test::Run::CmdLine::Trap::ProveApp: 0
  Test::Run::Trap::Obj: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Run-Plugin-ColorFileVerdicts
provides:
  Test::Run::CmdLine::Plugin::ColorFileVerdicts:
    file: lib/Test/Run/CmdLine/Plugin/ColorFileVerdicts.pm
    version: 0.0123
  Test::Run::Plugin::ColorFileVerdicts:
    file: lib/Test/Run/Plugin/ColorFileVerdicts.pm
    version: 0.0123
  Test::Run::Plugin::ColorFileVerdicts::CanonFailedObj:
    file: lib/Test/Run/Plugin/ColorFileVerdicts/CanonFailedObj.pm
  Test::Run::Plugin::ColorFileVerdicts::ColorBase:
    file: lib/Test/Run/Plugin/ColorFileVerdicts/ColorBase.pm
requires:
  MRO::Compat: 0
  Moose: 0
  Term::ANSIColor: 0
  Test::Run::CmdLine: 0.0121
  Test::Run::Core: 0.0122
  perl: 5.008
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: 0.0123
